# dataset path
ROOT: &DATA_ROOT /share2/home/wuzhi/USTCData/
B_ROOT: &BOX_ROOT /share2/home/wuzhi/workspace/rfmask/rfbox6.lmdb
# subset
# CATEGORIES: &CATEGORIES ['OCCLUSION']

MODEL_NAME: &MODEL_NAME RFMask
DATASET_NAME: &DATASET_NAME rf

# experiment name or current model name
EXPER: &EXPER 'base'

TRAIN:
    MODEL:
        NAME: *MODEL_NAME
        ARGS:
            BATCH_SIZE: &TRAIN_BATCH 12
            LEARNING_RATE: &LR 1.0e-4
    TRAINER:
        MAX_EPOCHS: 200
        PRECISION: 16
        GPUS: -1
        ACCELERATOR: gpu
        STRATEGY: ddp # ddp_find_unused_parameters_false
        SYNC_BATCHNORM: true
        RELOAD_DATALOADERS_EVERY_N_EPOCHS: 20
    TRAINSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *DATA_ROOT
            # B_ROOT: *BOX_ROOT
            MODE: train
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: true
            NUM_WORKERS: &TRAIN_NUM_WORKERS 8
    VALSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *DATA_ROOT
            # B_ROOT: *BOX_ROOT
            MODE: val
            # CATEGORIES: *CATEGORIES
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: false
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    CKPT_PATH:
    LOGGER:
        NAME: *EXPER

EVAL:
    MODEL:
        NAME: *MODEL_NAME
        CFG:
            BATCH_SIZE: &VAL_BATCH 1
            LEARNING_RATE: *LR
    CKPT_PATH: /share2/home/wuzhi/workspace/RFTrack/checkpoints/abs_coor/version_1/checkpoints/epoch=199-step=19399.ckpt
    VALSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *DATA_ROOT
            # B_ROOT: *BOX_ROOT
            MODE: val
            # CATEGORIES: *CATEGORIES
        LOADER:
            BATCH_SIZE: *VAL_BATCH
            SHUFFLE: false
            NUM_WORKERS: 0
    TRAINER:
        MAX_EPOCHS: 1
        ENABLE_CHECKPOINTING: false
        GPUS: [0]
        ACCELERATOR: gpu
        LOGGER: false
    EXPER: *EXPER


