DATA:
  TRAIN:
    TYPE: CIFAR10
    CFG:
      root: datasets/cifar
      train: True
      download: True
  VAL:
    TYPE: CIFAR10
    CFG:
      root: datasets/cifar
      train: False
      download: True
  BATCH_SIZE: 32
  NUM_WORKERS: 4

MODEL:
  MODEL:
    TYPE: resnet18
    CFG:
      num_classes: 10
  # LOSS: CrossEntropyLoss

SOLVER:
  NUM_EPOCHS: 40
  OPTIMIZER:
    TYPE: AdamW
    CFG:
      lr: 1.0e-3  # '.0' is required for PyYAML to match with float instead of str
      weight_decay: 1.0e-5
  SCHEDULER:
    TYPE: CosineAnnealingLR
    CFG:
      T_max: 10
