# dataset path
TRAIN_DATA: &TRAIN_DATA data/hiber_train.lmdb
VAL_DATA: &VAL_DATA data/hiber_val.lmdb
TEST_DATA: &TEST_DATA data/hiber_test.lmdb

# subset
CATEGORIES: &CATEGORIES ['WALK', 'MULTI', 'ACTION']

MODEL_NAME: &MODEL_NAME RFMask
DATASET_NAME: &DATASET_NAME hiber

# experiment name
EXPER: &EXPER 'rfmask_single'

TRAIN:
    MODEL:
        NAME: *MODEL_NAME
        BATCH_SIZE: &TRAIN_BATCH 60
        LEARNING_RATE: &LR 1.5e-4
        DUAL: false
    TRAINER:
        MAX_EPOCHS: 200
        PRECISION: 32
        DEVICES: [0]
        ACCELERATOR: gpu
        # STRATEGY: ddp # ddp_find_unused_parameters_false
        SYNC_BATCHNORM: false
        RELOAD_DATALOADERS_EVERY_N_EPOCHS: 0
        LOG_EVERY_N_STEPS: 15
    TRAINSET:
        DATASET: *DATASET_NAME
        ROOT: *TRAIN_DATA
        MODE: train
        CATEGORIES: *CATEGORIES
        VIEWS: &VIEWS [6]
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: true
            NUM_WORKERS: &TRAIN_NUM_WORKERS 8
    VALSET:
        DATASET: *DATASET_NAME
        ROOT: *VAL_DATA
        MODE: val
        CATEGORIES: *CATEGORIES
        VIEWS: *VIEWS
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: false
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    CKPT_PATH: 
    LOGGER:
        NAME: *EXPER

EVAL:
    MODEL:
        NAME: *MODEL_NAME
        BATCH_SIZE: &VAL_BATCH 1
        LEARNING_RATE: *LR
        THRESHOLD: 0.4
        EXPER: *EXPER
    CKPT_PATH: 
    VALSET:
        DATASET: *DATASET_NAME
        ROOT: *VAL_DATA
        MODE: val
        CATEGORIES: *CATEGORIES
        VIEWS: *VIEWS
        LOADER:
            BATCH_SIZE: *VAL_BATCH
            SHUFFLE: false
            NUM_WORKERS: 0
    TRAINER:
        MAX_EPOCHS: 1
        ENABLE_CHECKPOINTING: false
        DEVICES: [0]
        ACCELERATOR: gpu
        LOGGER: false


