# dataset path
TRAIN_DATA: &TRAIN_DATA /share2/home/wuzhi/workspace/RFMask/data/hiber_val.lmdb
VAL_DATA: &VAL_DATA /share2/home/wuzhi/workspace/RFMask/data/hiber_val.lmdb

# subset
CATEGORIES: &CATEGORIES ['WALK', 'MULTI', 'ACTION']

MODEL_NAME: &MODEL_NAME RFMask
DATASET_NAME: &DATASET_NAME hiber

# experiment name
EXPER: &EXPER 'base'

TRAIN:
    MODEL:
        NAME: *MODEL_NAME
        ARGS:
            BATCH_SIZE: &TRAIN_BATCH 2
            LEARNING_RATE: &LR 1.0e-4
    TRAINER:
        MAX_EPOCHS: 200
        PRECISION: 32
        DEVICES: -1
        ACCELERATOR: gpu
        STRATEGY: ddp # ddp_find_unused_parameters_false
        SYNC_BATCHNORM: true
        RELOAD_DATALOADERS_EVERY_N_EPOCHS: 10
        LOG_EVERY_N_STEPS: 15
    TRAINSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *TRAIN_DATA
            MODE: train
            CATEGORIES: *CATEGORIES
            VIEWS: &VIEWS [6]
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: true
            NUM_WORKERS: &TRAIN_NUM_WORKERS 4
    VALSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *VAL_DATA
            MODE: val
            CATEGORIES: *CATEGORIES
            VIEWS: *VIEWS
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: false
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    CKPT_PATH: /share2/home/wuzhi/workspace/rfmask/ours/trans_wma/lightning_logs/version_0/checkpoints/epoch=199-step=50599.ckpt
    LOGGER:
        NAME: *EXPER

EVAL:
    MODEL:
        NAME: *MODEL_NAME
        CFG:
            BATCH_SIZE: &VAL_BATCH 1
            LEARNING_RATE: *LR
    CKPT_PATH: /share2/home/wuzhi/workspace/RFTrack/checkpoints/abs_coor/version_1/checkpoints/epoch=199-step=19399.ckpt
    VALSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *VAL_DATA
            MODE: val
            CATEGORIES: *CATEGORIES
            VIEWS: *VIEWS
        LOADER:
            BATCH_SIZE: *VAL_BATCH
            SHUFFLE: false
            NUM_WORKERS: 0
    TRAINER:
        MAX_EPOCHS: 1
        ENABLE_CHECKPOINTING: false
        GPUS: [0]
        ACCELERATOR: gpu
        LOGGER: false
    EXPER: *EXPER


