# dataset path
TRAIN_DATA: &TRAIN_DATA data/hiber_train.lmdb
VAL_DATA: &VAL_DATA data/hiber_val.lmdb
TEST_DATA: &TEST_DATA data/hiber_test.lmdb

# subset
CATEGORIES: &CATEGORIES ['WALK']

MODEL_NAME: &MODEL_NAME RFMask
DATASET_NAME: &DATASET_NAME hiber

# experiment name
EXPER: &EXPER 'rfmask_debugged_new_split'

TRAIN:
    MODEL:
        NAME: *MODEL_NAME
        ARGS:
            BATCH_SIZE: &TRAIN_BATCH 60
            LEARNING_RATE: &LR 1.5e-4
    TRAINER:
        MAX_EPOCHS: 200
        PRECISION: 32
        DEVICES: [0]
        ACCELERATOR: gpu
        # STRATEGY: ddp # ddp_find_unused_parameters_false
        SYNC_BATCHNORM: false
        RELOAD_DATALOADERS_EVERY_N_EPOCHS: 0
        LOG_EVERY_N_STEPS: 15
        # PROFILER: pytorch
        # OVERFIT_BATCHES: 0.2
        # ACCUMULATE_GRAD_BATCHES: 3
    TRAINSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *TRAIN_DATA
            MODE: train
            CATEGORIES: *CATEGORIES
            VIEWS: &VIEWS [6]
            # SPLIT_VIDEO: true
            # HIBER_MODE: train
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: true
            NUM_WORKERS: &TRAIN_NUM_WORKERS 8
    VALSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *VAL_DATA
            MODE: val
            CATEGORIES: *CATEGORIES
            VIEWS: *VIEWS
            # SPLIT_VIDEO: true
            # HIBER_MODE: train
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: false
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    CKPT_PATH: 
    LOGGER:
        NAME: *EXPER

EVAL:
    MODEL:
        NAME: *MODEL_NAME
        ARGS:
            BATCH_SIZE: &VAL_BATCH 1
            LEARNING_RATE: *LR
    CKPT_PATH: checkpoints/rfmask_debugged_new_split/version_0/checkpoints/epoch=42-step=12556-mloss=0.11.ckpt
    VALSET:
        NAME: *DATASET_NAME
        DATASET:
            ROOT: *VAL_DATA
            MODE: val
            CATEGORIES: *CATEGORIES
            VIEWS: *VIEWS
            # SPLIT_VIDEO: true
            # HIBER_MODE: train
        LOADER:
            BATCH_SIZE: *VAL_BATCH
            SHUFFLE: false
            NUM_WORKERS: 0
    TRAINER:
        MAX_EPOCHS: 1
        ENABLE_CHECKPOINTING: false
        DEVICES: [0]
        ACCELERATOR: gpu
        LOGGER: false
    EXPER: *EXPER


