# dataset path
TRAIN_DATA: &TRAIN_DATA data/hiber_train.lmdb
VAL_DATA: &VAL_DATA data/hiber_val.lmdb
TEST_DATA: &TEST_DATA data/hiber_test.lmdb

# subset
CATEGORIES: &CATEGORIES ['ACTION']

MODEL_NAME: &MODEL_NAME RFPose2DMask
DATASET_NAME: &DATASET_NAME hiber_mask

# experiment name
EXPER: &EXPER 'rfpose2dmask'

TRAIN:
    MODEL:
        NAME: *MODEL_NAME
        BATCH_SIZE: &TRAIN_BATCH 2
        LEARNING_RATE: &LR 1.0e-3
    TRAINER:
        MAX_EPOCHS: 200
        PRECISION: 32
        DEVICES: [0]
        ACCELERATOR: gpu
        # STRATEGY: ddp_find_unused_parameters_false
        SYNC_BATCHNORM: false
        RELOAD_DATALOADERS_EVERY_N_EPOCHS: 0
        LOG_EVERY_N_STEPS: 15
        OVERFIT_BATCHES: 0.03
    TRAINSET:
        DATASET: *DATASET_NAME
        ROOT: *TRAIN_DATA
        MODE: train
        CATEGORIES: *CATEGORIES
        VIEWS: &VIEWS [6]
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: true
            NUM_WORKERS: &TRAIN_NUM_WORKERS 8
    VALSET:
        DATASET: *DATASET_NAME
        ROOT: *VAL_DATA
        MODE: val
        CATEGORIES: *CATEGORIES
        VIEWS: *VIEWS
        LOADER:
            BATCH_SIZE: *TRAIN_BATCH
            SHUFFLE: false
            NUM_WORKERS: *TRAIN_NUM_WORKERS
    CKPT_PATH:
    LOGGER:
        NAME: *EXPER

EVAL:
    MODEL:
        NAME: *MODEL_NAME
        BATCH_SIZE: &VAL_BATCH 1
        LEARNING_RATE: *LR
        THRESHOLD: 0.3
        EXPER: *EXPER
    CKPT_PATH: checkpoints/rfpose2dmask/version_0/checkpoints/epoch=199-step=9600.ckpt
    VALSET:
        DATASET: *DATASET_NAME
        ROOT: *TEST_DATA
        MODE: test
        CATEGORIES: *CATEGORIES
        VIEWS: *VIEWS
        LOADER:
            BATCH_SIZE: *VAL_BATCH
            SHUFFLE: false
            NUM_WORKERS: 0
    TRAINER:
        MAX_EPOCHS: 1
        ENABLE_CHECKPOINTING: false
        DEVICES: [0]
        ACCELERATOR: gpu
        LOGGER: false


